### ISSUE TITLE
on some models, some textures get extracted but not included in the model

### ISSUE THREAD

**Issue by julianbrunner** [niacdoial/blemd#13]
I have some models (specifically d_md.bmd from Twilight Princess (GC)), where during importing using blemd, some textures are recognized and exported by bmdview (they appear in the textures directory, but not included at all in the imported model (in this case, it's mostly the cyan markings on Midna's body). Interestingly enough, they are displayed correctly by the bmdview2 viewer application, so maybe that points to a problem with the importer rather than the underlying bmd decoder?

My knowledge of 3D models and Blender is very limited, so I'm not sure where to even start looking. If there is anything I can do to help narrow things down, I'd be happy to. I could of course also send you the model in question.

**Comment by niacdoial** [comment]
Hello!
For the other two issues you mentioned, I will try to provide a patch,
~~somewhat~~ soon.
As for this one, there is something that can be done now.
In the import dialog, there is a checkbox for "node materials". Using it
will generate better, more complete materials, using nodes.
The reason why it isn't checked by default is that it gets messy (and
broken) when one tries to export to a more common 3D format.
Then again, this option might need to be renamed.
Thanks for spotting those problems, and have a nice day.

**Comment by julianbrunner** [comment]
Hey,

Thank you very much for the quick reply. Now I feel silly for not even noticing that there were import options for the plugin. The node materials option actually fixed most of the problems. Some oddities still remain, but I have not yet figured out what exactly is going on there, I will report back once I know more.

One thing that is also still happening is that an "ERROR MATERIAL" that is completely blue is created. It seems like it is not assigned to any part of the mesh (having Blender select all vertices with that material seems to do nothing). Not sure if that causes any problems though.

I'm really grateful that this plugin works so well already and even more grateful that you are still doing development on it. :)

**Comment by niacdoial** [comment]
Actually, this error material is created to be pasted on the eventual 
parts of the mesh without any material information (Mayor Bo's house in 
TP has a bunch of those as an "outer shell").
As for still doing development on it... It is mainly when a bug is 
spotted. I don't have as much free as before since september, but it 
should get better in half a year, and I still can make a quick change 
every once in a while.




---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
