### ISSUE TITLE
"WARNING bpy.ops.import_mesh.bmd.matv2 found different ind tex block" Error Followed by a Crash

### ISSUE THREAD

**Issue by GANONdork123** [niacdoial/blemd#21]
When attempting to import this (and other) BMD's I get this error 

[model.bmd](https://drive.google.com/file/d/1GRhjkoZcbrmQgcZftmoKGgpsfvVnq05d/view?usp=sharing)

![image](https://user-images.githubusercontent.com/20745330/45347617-895cd480-b57a-11e8-9b95-5e47d21853b1.png)

The model appears to import properly but Blender will crash whenever I attempt to go into Edit mode with the mesh selected.

**Comment by niacdoial** [comment]
Hello!
I'll try to look into this when I'll have he time.

What I can already tell, though, is that the (very unclear) warnings tell that BleMD doesn't know how to use indirect texturing (yet?).

However, because that data isn't used afterwards, I don't know where this crash comes from. And since it happens when BleMD technically finished its job, it is going to be hard to debug.

So... yeah. I'll keep you updated.

**Comment by niacdoial** [comment]
Hello!
Sorry, I underestimated how busy I would be those last two weeks.
I uploaded an imperfect fix, which uses a 'black box' from the blender API: it prevents the crash, but it also looses some data on a bigger amount of meshes.
This is why the fix isn't active by default, but is enabled by the "validate mesh" checkbox.
I will keep working on it.
I hope it is enough for now.

**Comment by niacdoial** [comment]
Yeah it messes up the material indices.

I am trying to find the blender C code associated with the `mesh.validate()` function that prevents crashing but causes this mess, so I can reverse-engineer it.

PS: sorry for the somewhat late response

**Comment by niacdoial** [comment]
I uploaded a permanent fix to this blender-crashing problem.
I kept the `validate` option just in case, though, but labeled it as a last resort.
I will reverse-engineer the validation function gradually, seeing it is 1500 lines long (all subfunction included)

**Comment by GANONdork123** [comment]
Oops reopened by accident.
