### ISSUE TITLE
Issues with importing the add-on into Blender 2.79.

### ISSUE THREAD

**Issue by Ripp42** [niacdoial/blemd#23]
I get the following error when trying to add the addon into blender. I have no experience with Python, so I had no clue what this means: 
![problem](https://user-images.githubusercontent.com/44348388/47272550-5a605800-d555-11e8-92f2-c8e4b3b57e51.png)
I renamed both the .zip folder and the repository folder inside of it blemd. I've also tried just doing the repository folder without being in a .zip. As far as I know, I followed the instructions in the manual accurately but no matter what I try it's still not accepting the add-on.

**Comment by niacdoial** [comment]
Hello!
I already answered this earlier this morning with a mail, but it seems it didn't register yet.

Long story short, it was trying to get a file that only exists on my PC, due to bad cleaning after debugging.
I thought I fixed it a couple days ago, but it still didn't work.
I fixed it for real ten minutes ago.

I hope it wasn't too much of an inconvenience.

**Comment by niacdoial** [comment]
Hello!

You did nothing wrong, don't worry.

The short version is that it tried to access a file that only exists on my PC.

The long version is that I revamped the way Mat3 and MaterialV2 worked, and during the debugging process I compared how both versions (before and after) worked by running both of them at the same time, but forgot to clean up some of the references to the old version afterwards.

I'm almost sure I fixed that earlier this week, but I'll check later today (probably around 8:30 AM UTC)

**Comment by Ripp42** [comment]
Thank you for the quick response! So if I redownload it, it should be fixed?

**Comment by Ripp42** [comment]
Edit: I got it to work, thanks! For some reason, the model shows up as a huge armature sort of diamond shape, and when I clear that away the model is nowhere to be seen. But the textures do show up in the new folder, and the vertex count sounds right.

**Comment by niacdoial** [comment]
Oh that's normal. it's just that most models are so big that opengl decides that none of the faces are close enough to be worth rendering.
Just select it (right click on it by default) and scale it down (press s, drag mouse closer to the center of the screen, click to confirm, rince and repeat until the model is visible).
Also, what you saw was a bone, so part of an armature to control the model if it is supposed to be deformable (like a character for instance)

Sorry in advance if you already know some of this.

**Comment by Ripp42** [comment]
Thank you!

**Comment by Ripp42** [comment]
So far the program works great, this tool is really neat! Unfortunately, I'm encountering a problem with importing certain textures. Certain maps in Twilight Princess keep their textures in the stg_00.arc folder so some textures are missing when I import them. I know this isn't part of the issue report, but do you know some way to get the textures to import properly?

**Comment by niacdoial** [comment]
If you know what texture in that arc file is used and what name it should have according to the bmd/bdl model, you can copy it to the "P:\ath\to\model_bXX\Textures\",  converted as a TGA or DDS file, depending on the BleMD settings you use.
The texture can then be used next import.

**Comment by Ripp42** [comment]
Thank you very much! You've been extremely helpful!
