### ISSUE TITLE
Unable to import Link from Wind Waker GC

### ISSUE THREAD

**Issue by Jujo100** [niacdoial/blemd#27]
Hello,

First, thanks for taking the time to make this tool!

I'm trying to import Link and his animations from Wind Waker on the Gamecube. But when I try to do so Blender just freezes. 

The file i'm importing is cl.bdl

Here is the console output:
```
found bundled python: C:\Users\x\Desktop\blender-2.77-windows64\2.77\python
blemd
C:\Users\xf\Desktop\blender-2.77-windows64\2.77\scripts\addons\blemd\__init__.py
2019-03-22 09:54:29,815    DEBUG bpy.ops.import_mesh.bmd.main Load :
2019-03-22 09:54:29,839     INFO bpy.ops.import_mesh.bmd.vtx1 length of normal coordinates (4520) is not //3
```

Regards,

**Comment by niacdoial** [comment]
Hello,
I do not have this file, but what I can tell you is that it might be normal.
depending on the PC's performance, it might keep blender frozen for more than a solid minute, especially on large models or with many animations.
However, I don't remember where it tended to take the most time.

Regards,

**Comment by ajd-262** [comment]
@Jujo100 Was able to open Link (cl.bdl) with Blender 2.78c no problems by it self. For Animations (LkAnm.arc_dir\archive\bcks) I had to split them in half. Just move half of the .bck files out of LkAnm.arc_dir\archive\bcks and try importing again. It still took time to load.
