### ISSUE TITLE
"just where is this person's home page?" answer

### ISSUE THREAD

**Issue by nico** [niacdoial/blemd#32]
Hi, I happened to see this repo today. I can answer the open question about early history: bmdview2 was written by me, the homepage of it was (and is, but I don't maintain it anymore and haven't for years) http://amnoid.de/gc

**Comment by Avatarus-one** [comment]
Do you have any plans to continue support of BMDView2 or any other GameCube ripping tools?

**Comment by niacdoial** [comment]
oh cool! I changed the readme file on my machine so that it gets updated with the next commit.
Did you create the first bmdview too?
Or is that that "Yaz0r/Yaz0" person? (a person who might not exist, but is in my notes because I was just tired that day. Seriously that name is too close to the compression scheme used by some bck files?)

**Comment by nico** [comment]
I created bmdview 1 too, but I don't remember if I ever released it or if that was only on my computer. bmdview 1 started as a dumper, so it had to executables: One that read the input files and wrote a bunch of text, and a renderer that read that text output and then produced graphics. That was useful early on, but made loading verrrry slow. When I wrote bmdview2, I understood the formats well enough that I could do everything in one go.

Yaz0r is https://twitter.com/yaz0r . He wrote a bunch of gamecube code too, but as far as I know it's not open source. IIRC he might've answered some of my questions but otherwise didn't contribute to bmdview2.

@Avatarus-one: No, I'm pretty busy with other things these days :)

**Comment by ajd-262** [comment]
@nico I do wish that bmdview2 was on your page as assembled .exe. The only way I could get a copy of bmdview2 by a now dead link on a Youtube video. bmdview2 is quicker than Blender when you need to find an object and works well for static object.

**Comment by niacdoial** [comment]
now, the readme has been fixed. Can I close the "issue"?
