### ISSUE TITLE
Blender freezes when importing a model with a lot of animations

### ISSUE THREAD

**Issue by fullmoon8** [niacdoial/blemd#34]
I am trying to import mario's model and animations from super mario sunshine, however blender freezes up while importing.

Does it just take a while to import and unfreeze, or is this a crash?

**Comment by niacdoial** [comment]
Hi!

It depends on how long it was frozen.
I remember that on my other PC, importin a Link model took more than 2 full minutes.
However, if it gets blocked for one hour or something, maybe it's the same problem as in issue #33.
If that's the case, you should try an older version of blemd (https://github.com/niacdoial/blemd/commit/0d618dd6743b7fc3edefe47777fee855f6335531)

**Comment by Vicousvern** [comment]
I can confirm it does load animations, I managed to import Link and all his animations (300+), it hangs but leaving it will open in eventually.

**Comment by fullmoon8** [comment]
> I can confirm it does load animations, I managed to import Link and all his animations (300+), it hangs but leaving it will open in eventually.

I see. Also wow I never knew Link had so many different animations.

I suppose maybe my laptop is just not powerful enough to import many animations at once. Or I just didn't wait long enough

Either way, I ended up just importing less animations, which worked fine

**Comment by BeezBumba** [comment]
@Vicousvern Was it TP link, if so how did you set it up so was the .bmd file in the same folder as the bck files or how was it?
