### ISSUE TITLE
infinite loops when bmd file does not contain a tex section

### ISSUE THREAD

**Issue by lolRazor** [niacdoial/blemd#40]
![3068690cd5ca75ac8fd1c289d3898ef7](https://user-images.githubusercontent.com/73223203/96696932-555b5c80-1359-11eb-8ef8-97122b6ec717.png)
![801ccbfc76db468d7d51a263152dad6b](https://user-images.githubusercontent.com/73223203/96697002-673cff80-1359-11eb-8495-da7551989f82.png)
![1ec83e83958f7e0ee998efe23e5568cf](https://user-images.githubusercontent.com/73223203/96697041-73c15800-1359-11eb-84c9-ce5d173ddbb1.png)
 No clue why this isnt working

**Comment by Roseghost** [comment]
^ +1, no clue how to solve it

**Comment by niacdoial** [comment]
OK, I have no idea how I saw this issue (twice!) and never realised what the problem actually was (early End Of File)
so, er…
in BModel.py, now around line 464, there is a block of lines like this:
```python
        while strTag != "TEX" and not br.is_eof():  # "TEX1 tag is the last one every time"
            br.SeekCur(iSize)
            streamPos = br.Position()
            strTag = br.ReadFixedLengthString(3)
            _ = br.GetByte()
            iSize = br.ReadDWORD()
```

try to add those two lines:
```diff
        while strTag != "TEX" and not br.is_eof():  # "TEX1 tag is the last one every time"
            br.SeekCur(iSize)
            streamPos = br.Position()
+           if br.is_eof():
+               break
            strTag = br.ReadFixedLengthString(3)
            _ = br.GetByte()
            iSize = br.ReadDWORD()
```
does it fix the problem? If not, is the error message at least different ?

**Comment by CrbzBrandon** [comment]
so I no longer have the error message when doing this, but I have Blender which loads indefinitely trying to load the file

**Comment by niacdoial** [comment]
…right. This might be another bug altogether.
what does the stack trace look like when you do Ctrl-C in the terminal after it loaded for a while ? just to see what loop it might be stuck on.

**Comment by CrbzBrandon** [comment]
I open blender I load the file for a little while then I press ctrl+c?

**Comment by niacdoial** [comment]
yep!
in a terminal/console window, Ctrl+C means "interrupt!" instead of "copy"
You just need to actually show the terminal window first, with… I think the option is in the "windows" menu of the toolbar at the top of blender?

**Comment by CrbzBrandon** [comment]
![image](https://user-images.githubusercontent.com/82187532/158067179-9d01880a-7f16-4d89-8171-d0c7c73e73e4.png)
here is the error

**Comment by niacdoial** [comment]
ok.
now, just to know if the bug is in the python code or the C code, if you change the area of common.py around line 117 like this:
```diff
+   print("call start")
    temp = subprocess.run([exefile] + args, shell=False)
    if temp.stdout:
        log.info ("process output:\n %s", temp.stdout)
    if temp.stderr:
        log.error('process errors:\n %s', temp.stderr)
+    print("call end")
```

does blemd repeat "call start/call end" without stopping, or does it just freeze after saying "call start"?

**Comment by CrbzBrandon** [comment]
it does not write it in the console of blender it redoes the same thing as the screen above

**Comment by niacdoial** [comment]
oh sorry, I forgot to ask you to delete the images again.
but er… how much did you wait before using ctrl+C? Because if it hangs even without calling the bundled C program, it might have been too soon.

**Comment by CrbzBrandon** [comment]
if i do nothing it keeps spamming in blender console (read ic)

**Comment by niacdoial** [comment]
ooooh!
I see exactly where the bug is.
er… would you be able to recompile the bmdview.cpp file into the bmdview.exe program if I asked you to?
to know if I should send you the patch, or just put it in a commit. (probably not tonight though, it's getting late)

**Comment by CrbzBrandon** [comment]
I don't think so, I don't know much about coding

**Comment by niacdoial** [comment]
ok.
er… dang, I just realised I won't have access to a windows machine for a while, so compiling it myself won't be easy. bluh.

**Comment by CrbzBrandon** [comment]
I'll look into how to do it

**Comment by niacdoial** [comment]
er… thanks!

**Comment by CrbzBrandon** [comment]
I've tried looking at several tutorials and I just can't do it.

**Comment by niacdoial** [comment]
ok, no problem. I'll see what I can do on my side of things.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
Well, i don't think that it not working with 2.77 is much of an "issue" anymore

**Comment by niacdoial** [comment]
yeah, the title needs to be revamped

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
is there any BMD file without textures you can think of?
i might try tweaking the code to fix this

**Comment by niacdoial** [comment]
oh, I know what fix can be done, I just don't have a way to re-compile the c++ file for windows systems anymore

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
I'm trying to see if there's a different solution and that'd require a bmd file without textures

**Comment by niacdoial** [comment]
another solution would be to not call bmdview.exe whenever blemd detects that the Tex section is missing. (given that the first infinite loop can be solved with the patch in a message higher in this conversation)

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
that's what I was thinking of, but i need a file to test it with

**Comment by niacdoial** [comment]
I don't have one, I just asked CrbzBrandon  whenever I had a patch that I thought worked.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
Looking at the third image, it seems to be from pixelmon?

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
the directory structure matches, and pixelmon did use .bmd at some point

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
but it does not seem to be the same BMD as the one you're trying to load, I couldn't get STB or J3DView to view it either

**Comment by CrbzBrandon** [comment]
that's exactly what I'm trying to have also the model and texture of the pixelmon mod

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
it's a completely different format.
the pixelmon one has a blender signature in it, and doesn't have the magic `J3D` at offset 0x00

**Comment by CrbzBrandon** [comment]
so there is no way to open them?

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
Not that I'm aware of
