### ISSUE TITLE
3.0.1

### ISSUE THREAD

**Issue by OoLunar** [niacdoial/blemd#46]
As of commit 1c5ee9deca063d04bcbbbe0da14f56af9e7a0799, on Blender 3.0.1, I cannot find the Nintendo import option. I have enabled the blemd addon, and installed it as requested in the MANUAL.md file. I have restarted blender.

![image](https://user-images.githubusercontent.com/46751150/154864106-709827c5-06ea-4fef-9fff-cdfd3e16a2d9.png)
![image](https://user-images.githubusercontent.com/46751150/154864133-351443a0-2b3f-4a52-9ccb-2630ea1d4650.png)

**Comment by niacdoial** [comment]
yes, that's… an embarrassing issue. The reason it worked on my machine was the weird stuff in my developing setup
It should be fixed now.

**Comment by OoLunar** [comment]
Confirmed fix with commit e7faa7ce1f1c5d521d6ac1d97f8b786ae32ef2e5, thanks for the quick response time.
