### ISSUE TITLE
I get this error when I try to open a .bmd file with Blender

### ISSUE THREAD

**Issue by CrbzBrandon** [niacdoial/blemd#50]
![Capture d’écran 2022-03-07 151805](https://user-images.githubusercontent.com/82187532/157051862-ec5b32c2-def3-4606-9cc4-50807f66fd06.png)

**Comment by niacdoial** [comment]
Sounds like the same error than in issue #40.
does the partial fix suggested there work here?
I'll close this one as a duplicate for now, feel free to re-open it (or ask for it to be re-opened in issue #40) if you disagree.
