### ISSUE TITLE
Texture coordinate offsets are off

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [niacdoial/blemd#52]
When loading many different things, mainly from Super Mario galaxy you'd probably notice the textures are mapped completely wrong.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
nvm it's not the transforms, but the "mirroring", for it i'd say just use a pingpong node for each axis with a threshold of 1

**Comment by niacdoial** [comment]
er…
you might want to tick the "use complete materials" option when importing, the results are much better. the reason why it's not there by default is that it used to not export at all in fbx files and the like, although I didn't try this with more recent blender versions.
For the multiply-add node, it's much newer than my project. Actually, it's not even there in blender 2.83, which I want to keep compatibility for.
Also, I don't think does blender have one of those "pingpong nodes".

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
i meant a ping-pong math node

**Comment by niacdoial** [comment]
Ah, the ping-pong operation of the Vector Math node. I see.
Sadly, it also doesn't exist in blender 2.83.

**Comment by niacdoial** [comment]
oh wait no it's regular Math, not vector math

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
#53

**Comment by niacdoial** [comment]
[PR #53 has been merged]
does this mean that this issue can be closed ?

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
Yup
