### ISSUE TITLE
Will support for BCA animation file be added?

### ISSUE THREAD

**Issue by SuperGameCube** [niacdoial/blemd#62]
There are animations from a few 1st party GC games that I want to rip (mainly from MKDD), and they're in the bca format.
Unfortunately, blemd doesn't appear to support bca at the moment. Is there any chance that support for bca will be implemented in the near future?

**Comment by niacdoial** [comment]
Sadly, I don't think so, if only because I have no idea how that file type might be structured.
Though, if those animations are successfully imported by https://github.com/RenolY2/j3dview, I might have a chance to do that in the next… few years?

**Comment by TheAftermathDestroyer** [comment]
Is mkds gcgp almost done

**Comment by SuperGameCube** [comment]
Closed because I don't like being bothered by kids in random places
