### ISSUE TITLE
Can't Import The Wind Waker cl.bdl with animations

### ISSUE THREAD

**Issue by Captainkittyca2** [niacdoial/blemd#66]
I'm using blender 3.4+ and everytime i import toon link (cl.bdl) with even just one animation, it crahses blender. I haven't tried importing it without an animation, but I don't want to do that because I already know how to do that via a separate tool. I'm using this tool to get animations.

**Comment by niacdoial** [comment]
blender crash? that sounds awful, it should be able to handle a plugin failure…

Do you know how to start blender in a terminal, so you could show what it prints before/during this crash?

**Comment by Captainkittyca2** [comment]
@niacdoial Well by crash I mean blender freezes, for far longer than 5 or 10 minutes. For Twilight Princess, it works fine as long as i have 20 or less bck animations stored in the bck folder. But for The Wind Waker, even if I just have one animation in bck folder, it doesn't work.
![image](https://user-images.githubusercontent.com/68467449/212482105-7e60d460-cae2-4899-b654-66f375b0ab9f.png)

**Comment by niacdoial** [comment]
hm… that is weird, and not for a reason that's linked to this problem.

can you change line 71 in `__init__.py` from "`    if not logging.root.handlers:`" to "`    if True:`" and try again, please?
The problem should still be there, but the log should be far longer.

**Comment by Captainkittyca2** [comment]
I changed it but the log still looks the same in cmd so far. Do i have to wait 5 minutes or something for it to expand?

**Comment by Captainkittyca2** [comment]
![image](https://user-images.githubusercontent.com/68467449/212483210-e907a31a-ccee-4805-8520-616ce3297bc1.png)

**Comment by niacdoial** [comment]
no, the log it should be different. At least with a "load: " line near the start
…oh, you should restart blender between tests. f8-reloading often doesn't work, I learned that the hard way.

and yes, that is the change I was describing.

**Comment by Captainkittyca2** [comment]
i deid restart blender and the cmd, i even tried again restarting after you mentioned it, still nothing changed afaik. By restart I mean, i closed blender and cmd windows by clicking the X button at top right of the window for both, then i launched the cmd and blender again and tried it. Same result: 
![image](https://user-images.githubusercontent.com/68467449/212483729-438ae2a9-26c0-463e-96a7-1f5e11696237.png)

**Comment by niacdoial** [comment]
wait.
…I just saw the lines that start with the date and time. nevermind, all of that was on me.

**Comment by Captainkittyca2** [comment]
@niacdoial Can I send you the cl.bdl and onje of the bck files so you could test it?

**Comment by niacdoial** [comment]
I'ld rather not?
besides, from the log I see, I might know where the problem is.
just to confirm, can you do these other changes, please ?
``` diff
@ common.py, Line 111
+    log.info("pre, running (%s)", exefile)
    temp = subprocess.run([exefile] + args, shell=False)
+    log.info("post")
```
It should just add one or two messages to the log (in theory, just the "pre" one) and show the path "D:\Program Files\Blender\3.4\scripts\addons\blemd\bmdview.exe"
thanks!

**Comment by Captainkittyca2** [comment]
before: ![image](https://user-images.githubusercontent.com/68467449/212484840-913d907d-9798-47c1-9a3e-90d9470020c6.png)
After: 
![Uploading image.png…]()
Like this?

**Comment by niacdoial** [comment]
yep, like this. Thanks!

**Comment by Captainkittyca2** [comment]
sorry, it still doesn't expand, and i did exit and then launch blender again
![image](https://user-images.githubusercontent.com/68467449/212485214-68cd42c7-1745-4152-a819-cd27b139547a.png)

**Comment by niacdoial** [comment]
even at the end, after tex1?

**Comment by Captainkittyca2** [comment]
yeah

**Comment by Captainkittyca2** [comment]
[windwakeranim.zip](https://github.com/niacdoial/blemd/files/10418291/windwakeranim.zip)

**Comment by Captainkittyca2** [comment]
this has the setup i used for the bmd and bck

**Comment by Captainkittyca2** [comment]
bdl*

**Comment by niacdoial** [comment]
…ok, I'll see what I can do.
(maybe not right now, I have a few things to do in parallel)

**Comment by Captainkittyca2** [comment]
Thanks! and also thanks for making a tool that can make bck animations directly work in blender I've been looking for something like this for perhaps over a year now lel.

Here's me messing around with Twilight Princess stuff :)
![image](https://user-images.githubusercontent.com/68467449/212485710-ceb88dff-d2ce-4d3d-bd86-de7a00ed4bd0.png)

https://user-images.githubusercontent.com/68467449/212485724-65e24155-9a1b-4060-9215-04bbe117cd55.mp4

**Comment by niacdoial** [comment]
I can't read that video, so I'll assume it represents someone cheering.
and no problem!
