### ISSUE TITLE
SuperSpinDriver.bdl from galaxy 2 hangs.

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [niacdoial/blemd#71]
it just freezes.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
also happens for galaxy 1

**Comment by niacdoial** [comment]
I just uploaded changes to print more info to the terminal (printing messages like "just started this part of the code")
What are the messages it manages to print before freezing?

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
it's when it tries to read 4 FF bytes in a row

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
during Part1Entry line 37

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
Yup, now it loads correctly with animations, thanks!
