### ISSUE TITLE
Animation Error with Blender 3.0: "animation file doesn't apply as expected (error is 'Bone' object has no attribute 'use_inherit_scale')" On master Branch

### ISSUE THREAD

**Issue by linkyamato** [niacdoial/blemd#82]
i don't know why this happens. the model and the textures import as expected (I am also getting this error for textures but they load anyway: node (GLSL) materials went wrong.Falling back to incomplete materials.(error is bpy_prop_collection[index]: index 0 out of range, size 0)

i had to use blender 2.77, for this repo, checkout 4d26777 and zip it for backwards compatibility as mentioned here: https://github.com/niacdoial/blemd/issues/33#issuecomment-869100043

**Comment by niacdoial** [comment]
I added a commit or two to work under recent versions of blender (plus a new branch to backport some of the newer stuff to blender 2.7x)
tell me if I managed to squash that particular issue!

**Comment by linkyamato** [comment]
works like a charm for 4.0!
thank you for maintaining this
