### ISSUE TITLE
ARCTool.py does not support .arc

### ISSUE THREAD

**Issue by BeezBumba** [niacdoial/blemd#87]
I found that the easiest way because the other ways looked outdated. The SZS Tools stuff was made in like 2014!

**Comment by niacdoial** [comment]
I have no idea what you are talking about.
what's this "arctool.py" thing?

**Comment by niacdoial** [comment]
ok now I think I have the context as what you mean.
just to check: did you manage to make ARCtool.py work? just in case, I switched the link in the readme to a more recent fork of ARCTool.py, which does not depend on a long-dead version of python

**Comment by BeezBumba** [comment]
Sorry, I just ended up using Wii Explorer. It's something else to extract all the stuff but thanks for the response.
