### ISSUE TITLE
custom normals not imported in Blender 4.1+

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [niacdoial/blemd#91]
when importing any mesh, the following error is given:
`ERROR    bpy.ops.import_mesh.bmd.main Normals weren't set (error is 'Mesh' object has no attribute 'create_normals_split') (x1)`
this is due to differences in the 3.6+ API, where `create_normals_split` has been replaced deprecated in favor of `Mesh.corner_normals`

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
simply removing that line seems to fix the issue

**Comment by niacdoial** [comment]
kinda took a while, but yeah, that call first turned useless, then got removed from the API altogether.
the latest commit should take care of this
thanks for spotting all this!
