### ISSUE TITLE
Weird bone rotation on animation import

### ISSUE THREAD

**Issue by FonzieMcCloud** [niacdoial/blemd#93]
Hey, i am currently trying to import some windwaker animations into blender using blemd but i get this weird arm rotations from time to time. 

ive tried all import setting combinations (disable axis conversation on and off, use smallest rotation on and off etc) but it always looks like this;

![GIF 13-11-2024 14-40-01](https://github.com/user-attachments/assets/a4a70df7-98a9-4dfe-b9f4-b9a4eb85de75)

this is the animation and how it looks like in bmdview2. 

![GIF 13-11-2024 14-37-30](https://github.com/user-attachments/assets/9a3bed4f-8c29-4a15-b532-719963d1eeab)

any idea whats wrong?

**Comment by FonzieMcCloud** [comment]
here is also a screenshot of the animation curve that i think is causing the problem (shoulder bone)

![boneCapture](https://github.com/user-attachments/assets/d659b91e-3e20-4979-b2f2-433d1ad70c82)

**Comment by FonzieMcCloud** [comment]
![image](https://github.com/user-attachments/assets/1d37b468-45ed-4486-ae8d-4d442481fe2b)

**Comment by niacdoial** [comment]
hello!
...okay, actually thank you for reminding me of this issue lol.

sadly, it's something I already encountered, but never managed to fix (take a look at issue #83)

I will try again, but I think this time I'll ask you to give me some data for me to try tweaks to the code.
here's a modified `pseudobones.py` which should print the needed data to the terminal:
[pseudobones.zip](https://github.com/user-attachments/files/17822291/pseudobones.zip)
you just need to:
- replace your installed blemd's `pseudobones.py` with the one in there,
- replace the string "BONE_NAME_HERE" with the name of the bone with these curves (line 466)
- enable the terminal (I think on windows it's in the "window" or "help" menu)
- import the model, making sure only the animation with a problem will load (by moving the other bck files away)
- copy the block of data that looks a bit like (here is an example for a bone named "mask4"):

```
----------------------------------------------------------------------------------------------------
For: mask4
default rotation: <Euler (x=0.0000, y=-0.0000, z=0.0000), order='XYZ'>
Animations: KeyFrames
pos_x: OrderedDict([(0, (105.68114471435547, 0.12468336522579193, 0.12468336522579193)), (3, (105.33346557617188, -0.33043861389160156, -0.33043861389160156)), (7, (104.61221313476562, 0.1259898990392685, 0.1259898990392685)), (12, (105.65895080566406, 0.06174086779356003, 0.06174086779356003)), (17, (105.71543884277344, -0.0007533999742008746, -0.0007533999742008746))])
pos_y: OrderedDict([(0, (450.4278259277344, -0.44719696044921875, -0.44719696044921875)), (6, (448.76885986328125, 0.24829863011837006, 0.24829863011837006)), (11, (450.5578918457031, 0.12760163843631744, 0.12760163843631744)), (17, (450.4072265625, -0.02368926629424095, -0.02368926629424095))])
pos_z: OrderedDict([(0, (-147.99803161621094, -0.08576393127441406, -0.08576393127441406)), (11, (-147.4302520751953, -0.09525776654481888, -0.09525776654481888)), (17, (-148.03048706054688, -0.030136100947856903, -0.030136100947856903))])
rot_x: OrderedDict([(0, (-1.4182611121995181, -0.0005752427954571154, -0.0005752427954571154)), (1, (-1.4188363549949752, 0.011025486912928047, 0.011025486912928047)), (5, (-1.3056093980891663, 0.013134710496270803, 0.013134710496270803)), (8, (-1.3439589177863074, -0.030296120560741414, -0.030296120560741414)), (10, (-1.407331499085833, -0.02348908081449888, -0.02348908081449888)), (14, (-1.4276567445253177, 0.002684466378799872, 0.002684466378799872)), (17, (-1.4203703357828608, 0.0009587379924285257, 0.0009587379924285257))])
rot_y: OrderedDict([(0, (1.207530501463728, 0.01083373931444234, 0.01083373931444234)), (4, (1.2305402132820127, -0.0005752427954571154, -0.0005752427954571154)), (11, (1.2152004054031564, -0.002205097382585609, -0.002205097382585609)), (17, (1.2081057442591854, -0.00019174759848570515, -0.00019174759848570515))])
rot_z: OrderedDict([(0, (-1.3906494580175766, 0.006231796950785417, 0.006231796950785417)), (1, (-1.384417661066791, 0.01754490526144202, 0.01754490526144202)), (5, (-1.2570013818730401, 0.01227184630308513, 0.01227184630308513)), (8, (-1.3053217766914378, -0.03451456772742693, -0.03451456772742693)), (10, (-1.3764601357296344, -0.02636529479178446, -0.02636529479178446)), (14, (-1.400140964142619, 0.0027803401780427247, 0.0027803401780427247)), (17, (-1.392375186403948, 0.0010546117916713782, 0.0010546117916713782))])
scl_x: OrderedDict([(0, (1.0, 0, 0)), (17, (1.0, 0, 0))])
scl_y: OrderedDict([(0, (1.0, 0, 0)), (17, (1.0, 0, 0))])
scl_z: OrderedDict([(0, (1.0, 0, 0)), (17, (1.0, 0, 0))])

----------------------------------------------------------------------------------------------------
```

Thanks!
Have a nice day!

**Comment by FonzieMcCloud** [comment]
nice! thanks a lot. here is the log :)



`For: Lshoulder_jnt
default rotation: <Euler (x=0.0000, y=-0.0000, z=0.0001), order='XYZ'>
Animations: KeyFrames
pos_x: OrderedDict([(0, (19.653684616088867, 0, 0)), (19, (19.653684616088867, 0, 0))])
pos_y: OrderedDict([(0, (-0.08794499933719635, 0, 0)), (19, (-0.08794499933719635, 0, 0))])
pos_z: OrderedDict([(0, (0.0, 0, 0)), (19, (0.0, 0, 0))])
rot_x: OrderedDict([(0, (1.1704273411567443, 0.047553404424454875, 0.047553404424454875)), (1, (1.218172493179685, 0.05733253194722584, 0.05733253194722584)), (6, (1.567344870022154, 0.04295146206079795, 0.04295146206079795)), (10, (1.6687793496210919, 0.04621117123505494, 0.04621117123505494)), (12, (1.8334905367203127, 0.14093448488699328, 0.14093448488699328)), (13, (2.010281822524133, 0.21782527187976106, 0.21782527187976106)), (14, (2.2693328280783205, 0.2755412990239583, 0.2755412990239583)), (15, (2.561556168170535, 0.2649951811072445, 0.2649951811072445)), (16, (2.799514937891295, 0.19308983167510507, 0.19308983167510507)), (18, (3.0236678805210846, 0.05196359918962609, 0.05196359918962609)), (19, (3.051854777498483, 0.02799514937891295, 0.02799514937891295))])
rot_y: OrderedDict([(0, (-1.0789637366790628, -0.027419906583455837, -0.027419906583455837)), (4, (-1.1756045263158583, -0.021859226227370385, -0.021859226227370385)), (7, (-1.2509613325207403, -0.030679615757712823, -0.030679615757712823)), (12, (-1.4141385388320755, -0.027228158984970132, -0.027228158984970132)), (15, (-1.4494200969534452, 0.009587379924285258, 0.009587379924285258)), (19, (-1.3336045474680793, 0.03681553890925539, 0.03681553890925539))])
rot_z: OrderedDict([(0, (-2.691752787542329, -0.05177185159114039, -0.05177185159114039)), (1, (-2.743524639133469, -0.05752427954571154, -0.05752427954571154)), (6, (-3.103818376688109, -0.07133010663668231, -0.07133010663668231)), (10, (-3.421927642575894, -0.11447331629596597, -0.11447331629596597)), (12, (-3.731600014130308, -0.2168665338873325, -0.2168665338873325)), (13, (-3.9856655821238673, -0.29605829206192874, -0.29605829206192874)), (14, (-4.323716598254165, -0.35492480479704025, -0.35492480479704025)), (15, (-4.695515191717948, -0.34437868688032647, -0.34437868688032647)), (16, (-5.012473972014818, -0.2715145994557585, -0.2715145994557585)), (18, (-5.389258003039229, -0.12501943421267975, -0.12501943421267975)), (19, (-5.488775006653309, -0.09932525601559526, -0.09932525601559526))])
scl_x: OrderedDict([(0, (1.0, 0, 0)), (19, (1.0, 0, 0))])
scl_y: OrderedDict([(0, (1.0, 0, 0)), (19, (1.0, 0, 0))])
scl_z: OrderedDict([(0, (1.0, 0, 0)), (19, (1.0, 0, 0))])`

**Comment by niacdoial** [comment]
hello!
I... think this is not the right data, sorry.
I have something to view and test it, but I can't reproduce the bug yet.

the last line should probably be `scl_z: OrderedDict([(0, (1.0, 0, 0)), (32, (1.0, 0, 0))])`, rather than `scl_z: OrderedDict([(0, (1.0, 0, 0)), (19, (1.0, 0, 0))])`  (32 instead of 19), because that's the length of the animation which has a problem, from your screenshot.

**Comment by FonzieMcCloud** [comment]
_WW_Link_Climb.zip (edit by repo owner: link removed (...lol))

hm. weird, these are the files (bmd and bck) i use. and then i logged the Lshoulder_jnt bone

**Comment by niacdoial** [comment]
okay I see.
the graph you gave didn't correspond to the animation you showed
lemme check again why my curves don't reproduce the bug then

**Comment by niacdoial** [comment]
done!
the latest change to the code should have fixed what the "use 'smallest rotation rule' on animations" checkbox does.
do you confirm that this works on your side as well?

**Comment by FonzieMcCloud** [comment]
it works very much good now. 
great success! much nice!
thanks a lot!

**Comment by FonzieMcCloud** [comment]
great success !
